version: '3.8'

services:
  fungal-intelligence:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - ENV=development
      - PYTHONPATH=/app/src
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
  logs: